manifest:

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: my_github
      url-base: https://github.com/filiplindau
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display-view
      remote: my_github
      revision: ea0b2b1
    # - name: zmk-behavior-contextual
    #   remote: my_github
    #   revision: master # The branch name of your module repo
  self:
    path: config

